apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: wil-app.bladash.lol
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wil-app
              port:
                number: 8888
    - host: localhost
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wil-app
              port:
                number: 8888